### ISSUE TITLE
Error: Cannot find module 'postcss'

### ISSUE THREAD

**Issue by eeylomwjb** [SchOJ/dmoj-dockercompose#1]
You made tremendous work creating this repository and wiki. I highly appreciate it. 
Standard installation via [docs.dmoj.ca](https://docs.dmoj.ca/#/site/installation) is very unstable and time consuming. 
However after I do ```docker-compose build``` I get this error:
```
internal/modules/cjs/loader.js:983
  throw err;
  ^

Error: Cannot find module 'postcss'
Require stack:
- /usr/lib/node_modules/postcss-cli/index.js
- /usr/lib/node_modules/postcss-cli/bin/postcss
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:980:15)
    at Function.Module._load (internal/modules/cjs/loader.js:862:27)
    at Module.require (internal/modules/cjs/loader.js:1042:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/usr/lib/node_modules/postcss-cli/index.js:13:17)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Module.require (internal/modules/cjs/loader.js:1042:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/lib/node_modules/postcss-cli/index.js',
    '/usr/lib/node_modules/postcss-cli/bin/postcss'
  ]
}
ERROR: Service 'site' failed to build : The command '/bin/sh -c ./make_style.sh &&     echo yes | python3 manage.py collectstatic &&     python3 manage.py compilemessages &&     python3 manage.py compilejsi18n' returned a non-zero code: 1
```

**Comment by outloudvi** [comment]
https://github.com/SchOJ/dmoj-site/commit/0d24974f4524c95a5b3443c6ab5c7956865322f0

**Comment by outloudvi** [comment]
By the way, recently we are following up `schoj/site` with upstream, and thus our site fork might be broken for now. To use the upstream site code, don't update your submodules and just do the modification as described in https://github.com/SchOJ/dmoj-site/commit/6aeba553f2108d999000ac3079270f8ea3bad0f4.
